# Generated by Django 3.2.9 on 2021-12-01 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ROM', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
    ]
