# Generated by Django 3.2.9 on 2021-11-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROM', '0002_auto_20211130_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('regular', 'regular'), ('commercial', 'commercial'), ('personalized', 'personalized')], default='regular', max_length=100),
        ),
    ]
