# Generated by Django 3.2.9 on 2022-01-10 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ROM', '0005_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftcard',
            name='order_id',
        ),
        migrations.AddField(
            model_name='giftcard',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ROM.customer'),
        ),
    ]
