# Generated by Django 3.2.9 on 2022-02-21 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ROM', '0007_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftcard',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='giftcard',
            name='service_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ROM.service'),
        ),
    ]
