# Generated by Django 3.2.9 on 2022-03-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROM', '0010_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='message',
            field=models.TextField(default='Typehere...'),
        ),
    ]
