# Generated by Django 3.2.9 on 2022-03-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROM', '0011_inquiry_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='order_id',
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='message',
            field=models.TextField(),
        ),
    ]
