# Generated by Django 3.2.9 on 2022-03-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROM', '0013_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftcard',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='giftcard',
            name='service_id',
        ),
        migrations.RemoveField(
            model_name='giftcard',
            name='start_date',
        ),
        migrations.AddField(
            model_name='giftcard',
            name='email',
            field=models.CharField(default='Some String', max_length=100),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='message',
            field=models.TextField(default='Some String'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='name',
            field=models.CharField(default='Some String', max_length=100),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
