# Generated by Django 3.2.9 on 2022-04-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROM', '0016_cart_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='recipient_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
