# Generated by Django 3.2.9 on 2022-04-16 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ROM', '0017_auto_20220405_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=100)),
                ('home', models.CharField(max_length=100)),
                ('bedroom', models.CharField(max_length=100)),
                ('sqrft', models.CharField(max_length=100)),
                ('floors', models.IntegerField(blank=True, null=True)),
                ('occupants', models.IntegerField(blank=True, null=True)),
                ('space', models.CharField(max_length=100)),
                ('no_pets', models.IntegerField(blank=True, null=True)),
                ('npets', models.IntegerField(blank=True, null=True)),
                ('frequency', models.CharField(max_length=100)),
                ('schedule', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('payment', models.CharField(max_length=100)),
                ('card_number', models.IntegerField(blank=True, null=True)),
                ('card_name', models.CharField(max_length=100)),
                ('valid', models.IntegerField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ROM.order')),
            ],
        ),
    ]
