# Generated by Django 3.2.9 on 2022-04-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROM', '0018_orderdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='bedroom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='sqrft',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='zip',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
