# Generated by Django 3.2.9 on 2022-04-19 06:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ROM', '0019_auto_20220418_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service_id',
        ),
        migrations.AddField(
            model_name='order',
            name='Payment',
            field=models.CharField(choices=[('paypal', 'paypal'), ('credit or debit card', 'credit or debit card')], default='Paypal', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='about',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='bedroom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='card_name',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='card_number',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='ccv',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='floors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='frequency',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='home',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='no_pets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='npets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='occupants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='schedule',
            field=models.CharField(default=datetime.datetime(2022, 4, 19, 6, 58, 8, 456792, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='service_category',
            field=models.CharField(choices=[('regular', 'regular'), ('commercial', 'commercial'), ('personalized', 'personalized')], default='regular', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='space',
            field=models.CharField(default=1200, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='sqrft',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='subject',
            field=models.CharField(default='Order', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='valid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='zip',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ROM.order'),
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
    ]
