# Generated by Django 3.2.9 on 2022-04-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROM', '0022_alter_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Payment',
            field=models.DateTimeField(choices=[('paypal', 'paypal'), ('credit or debit card', 'credit or debit card')], default='Paypal', max_length=100),
        ),
    ]
