# Generated by Django 3.2.9 on 2022-04-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROM', '0023_alter_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Payment',
            field=models.CharField(choices=[('paypal', 'paypal'), ('credit or debit card', 'credit or debit card')], default='Paypal', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='schedule',
            field=models.DateTimeField(max_length=100),
        ),
    ]
