# Generated by Django 3.2.9 on 2022-04-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROM', '0024_auto_20220421_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='no_pets',
            new_name='bathroom',
        ),
        migrations.AddField(
            model_name='order',
            name='pets',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
