# Generated by Django 3.2.9 on 2022-04-27 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ROM', '0025_auto_20220421_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Payment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ccv',
        ),
        migrations.RemoveField(
            model_name='order',
            name='valid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='description',
        ),
    ]
